Docs
ClimateImpactLab/jrnr pull request #36
Opened 2018-01-11 01:35 UTC by jgerardsimcock

- [x ] closes #35 
 - [ ] tests added / passed
 - [ x] docs reflect changes
 - [ x] passes ``flake8 jrnr tests docs``
 - [ x] entry in HISTORY.rst

Adds documentation to use jrnr in interactive mode as well as batch mode.

2018-01-11 06:21 UTC, delgadom approved these changes

2018-01-11 06:21 UTC, delgadom commented on docs/usage.rst
> +As you can see, if you setting up logging, the logging information will print to the terminal to your terminal se
to your terminal se...?

2018-01-11 06:21 UTC, delgadom commented on docs/tas.py
> +'''
should this file be here?

2018-01-11 06:21 UTC, delgadom commented on docs/usage.rst
> +In your directory where you are running your job, `jrnr` creates a `locks` directory. In this `locks` directory, for each job in your set of batch jobs a file is created with the following structure
this whole file is fantastic. thank you!!!

2018-01-11 17:59 UTC, jgerardsimcock commented on docs/tas.py
> +'''
This file I want show as a template for setting up a jrnr script. We can also link to impactlab documentation on gitlab for more examples but I wanted to have something in the docs.

2018-01-11 18:17 UTC, jgerardsimcock commented on docs/usage.rst
> +As you can see, if you setting up logging, the logging information will print to the terminal to your terminal se
nice catch!

2018-01-11 18:40 UTC, delgadom requested changes

2018-01-11 18:40 UTC, delgadom commented on docs/tas.py
> +'''
ok. then can you link to this file somewhere in the actual docs? right now I don't see it anywhere in the navigation.

2018-01-11 19:17 UTC, jgerardsimcock commented on docs/tas.py
> +'''
Just pushed. There is now a tas.rst file that references the tas.py file. I followed the setup from this: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html#example-google

2018-01-11 19:52 UTC, delgadom requested changes

2018-01-11 19:52 UTC, delgadom commented on docs/tas.py
> +'''
but there is no way to access this file. have you tried building it and using the site? as far as I can tell, the user can't get to tas.rst.

You could either include tas.rst in the table of contents, or you could include a link to it in the usage file. Or both. But right now this file is truly an orphan. The other way you could do this is to allow the user to download tas.py, with a download directive. I'm agnostic about how you do it, but right now this page is inaccessible. There are a bunch of examples of including python scripts in a documentation page in the documentation repo, as well as the datafs docs. Let me know if you want help with this, but it should just be a matter of doing an internal hyperlink to the tas.rst header.

2018-01-11 19:55 UTC, delgadom commented
looks like you removed `modules.rst` from the index, but didn't remove the file? and why did you remove modules.rst? that's how the autodoc works

on travis:
/home/travis/build/ClimateImpactLab/jrnr/docs/modules.rst:document isn't included in any toctree

2018-01-11 19:56 UTC, delgadom commented
probably running `sphinx-apidoc` again would be a good idea, just to make sure all the modules/methods get included in the documentation

2018-01-12 01:47 UTC, delgadom approved these changes

2018-01-17 00:52 UTC, merged